#! /usr/bin/env python
# encoding: utf-8

top = '.'
out = 'build'

def options(opt):
    opt.load('compiler_cxx')

def configure(conf):
    conf.load('compiler_cxx')
    
    # conf.env.INCLUDES_mylib = ['dir_to_mylib_includes']
    # conf.env.LIBPATH_mylib = ['dir_to_mylib_libs']
    # conf.env.LIB_mylib = 'mylib'

    # load waf_conan_libs_info.py from generator (required deps/libs path)
    conf.load('waf_conan_libs_info', tooldir='.')

    # load waf_conan_toolchain.py from build helper (conan settings -> waf settings)
    conf.load('waf_conan_toolchain', tooldir='.')

def build(bld):
    bld.program(source='main.cpp', target='app', use='mylib')
